
# cargo ndk -t armeabi-v7a -t arm64-v8a -t x86 -t x86_64 -o ./BinderServer/app/src/main/jnilibs build --release
[tasks.build]
command = "cargo"
args = [
    "ndk",
    "-t",
    "armeabi-v7a",
    "-t",
    "arm64-v8a",
    "-t",
    "x86",
    "-t",
    "x86_64",
    "-o",
    "./BinderServer/app/src/main/jnilibs",
    "build",
    "--release",
]
